### ISSUE TITLE
"Implement me. Unknown stdin file type!" error thrown when running headless process in win32

### ISSUE THREAD

**Issue by jakelauer** [sindresorhus/get-stdin#20]
Hi there - I encountered this while attempting to run PostCSS commands via the PostCSS-CLI command line implementation. 

The exact error is as shown:

```
internal/process/stdio.js:82

        throw new Error('Implement me. Unknown stdin file type!');
        ^
    Error: Implement me. Unknown stdin file type!
    at process.getStdin [as stdin] (internal/process/stdio.js:82:15)
    at Object.<anonymous> (C:\Users\myusername\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\5xs3acz0.hfk\Resources\nodejs\node_modules\get-stdin\index.js:2:20)

    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

    at Object.<anonymous> (C:\Users\myusername\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\5xs3acz0.hfk\Resources\nodejs\node_modules\postcss-cli\index.js:6:15)

```

I found a similar issue in Angular here: https://github.com/angular/angular-cli/issues/4870

They solved it like this:
https://github.com/angular/angular-cli/commit/4af7a429205636e0a7a2fb6675cb4f389f80923d

Let me know if you need more information - I am very new to Node so you might need to simplify any questions you have for me.

**Comment by sindresorhus** [comment]
Open an issue on https://github.com/nodejs/node/issues Seems Node.js is missing code to handle that.
